import Head from "next/head";
import SignIn from "./login.js";

export default function Home() {
  console.log('azz');

  return (
    <div className="h-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignIn />
    </div>
  );
}
